# Add a label to any pull request whose head branch matches the specified pattern.
'enhancement':
  - head-branch: ['^feature/']
'bug':
  - head-branch: ['^bug/']
'chore':
  - head-branch: ['^chore/']
'refactor':
  - head-branch: ['^refactor/']
'documentation':
  - head-branch: ['^doc/']
'github_actions':
  - head-branch: ['^dependabot/gradle/org.sonarqube-']
