package com.apptasticsoftware.rssreader.module.podcast;

import com.apptasticsoftware.rssreader.util.Default;
import nl.jqno.equalsverifier.EqualsVerifier;
import org.junit.jupiter.api.Test;

import java.io.InputStream;
import java.time.Duration;
import java.util.List;
import java.util.stream.Collectors;

import static com.github.npathai.hamcrestopt.OptionalMatchers.*;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PodcastRssReaderTest {

    @Test
    @SuppressWarnings({"java:S5961", "java:S5738"})
    void example1() {
        var items = new PodcastRssReader().read(fromFile("podcast/example1.xml"))
                .collect(Collectors.toList());

        assertEquals(4, items.size());

        var liveItem = items.get(0);
        assertTrue(liveItem.isPodcastLiveItem());
        assertThat(liveItem.getPodcastLiveItemStatus(), isPresentAndIs("live"));
        assertThat(liveItem.getPodcastLiveItemStart(), isPresentAndIs("2021-09-26T07:30:00.000-0600"));
        assertThat(liveItem.getPodcastLiveItemStartAsZonedDateTime(), isPresentAndIs(Default.getDateTimeParser().parse("2021-09-26T07:30:00.000-0600")));
        assertThat(liveItem.getPodcastLiveItemEnd(), isPresentAndIs("2021-09-26T09:30:00.000-0600"));
        assertThat(liveItem.getPodcastLiveItemEndAsZonedDateTime(), isPresentAndIs(Default.getDateTimeParser().parse("2021-09-26T09:30:00.000-0600")));
        assertThat(liveItem.getTitle(), isPresentAndIs("Podcasting 2.0 Live Show"));
        assertThat(liveItem.getDescription(), isPresentAndIs("A look into the future of podcasting and how we get to Podcasting 2.0!"));
        assertThat(liveItem.getLink(), isPresentAndIs("https://example.com/podcast/live"));
        assertThat(liveItem.getIsPermaLink(), isPresentAndIs(true));
        assertThat(liveItem.getGuid(), isPresentAndIs("https://example.com/live"));
        assertThat(liveItem.getItunesImage(), isPresentAndIs("https://behindthesch3m3s.com/wp-content/uploads/2023/01/v4v-storm-good-quality.gif"));
        assertThat(liveItem.getPodcastAlternateEnclosures().size(), is(1));
        assertThat(liveItem.getPodcastAlternateEnclosures().get(0).getType(), is("audio/mpeg"));
        assertThat(liveItem.getPodcastAlternateEnclosures().get(0).getLength(), is(312L));
        assertThat(liveItem.getPodcastAlternateEnclosures().get(0).isDefaults(), is(true));
        assertThat(liveItem.getPodcastAlternateEnclosures().get(0).getLang(), is("en"));
        assertThat(liveItem.getPodcastAlternateEnclosures().get(0).getRel(), is("default"));
        assertThat(liveItem.getPodcastAlternateEnclosures().get(0).getCodecs(), is("video/mp4"));
        assertThat(liveItem.getPodcastAlternateEnclosures().get(0).getSources().size(), is(2));
        assertThat(liveItem.getPodcastAlternateEnclosures().get(0).getSources().get(0).getUri(), is("https://example.com/pc20/livestream"));
        assertThat(liveItem.getPodcastAlternateEnclosures().get(0).getSources().get(1).getUri(), is("https://example.com/file-1080.torrent"));
        assertThat(liveItem.getPodcastAlternateEnclosures().get(0).getSources().get(1).getContentType(), isPresentAndIs("application/x-bittorrent"));
        assertThat(liveItem.getEnclosures().size(), is(1));
        assertThat(liveItem.getEnclosures().get(0).getUrl(), is("https://example.com/pc20/livestream?format=.mp3"));
        assertThat(liveItem.getEnclosures().get(0).getType(), is("audio/mpeg"));
        assertThat(liveItem.getEnclosures().get(0).getLength(), isPresentAndIs(312L));
        assertThat(liveItem.getPodcastContentLinks().size(), is(2));
        assertThat(liveItem.getPodcastContentLinks().get(0).getContentLink(), is("YouTube!"));
        assertThat(liveItem.getPodcastContentLinks().get(0).getHref(), is("https://youtube.com/pc20/livestream"));
        assertThat(liveItem.getPodcastContentLinks().get(1).getContentLink(), is("Twitch!"));
        assertThat(liveItem.getPodcastContentLinks().get(1).getHref(), is("https://twitch.com/pc20/livestream"));
        assertTrue(liveItem.getPodcastChat().isPresent());
        assertThat(liveItem.getPodcastChat().get().getServer(), is("jabber.example.com"));
        assertThat(liveItem.getPodcastChat().get().getProtocol(), is("xmpp"));
        assertThat(liveItem.getPodcastChat().get().getAccountId(), is("jsmith@jabber.example.org"));
        assertThat(liveItem.getPodcastChat().get().getSpace(), isPresentAndIs("myawesomepodcast@jabber.example.org"));

        for (PodcastItem podcastItem : items) {
            var channel = (PodcastChannel) podcastItem.getChannel();
            assertThat(channel.getPodcastGuid(), is("y0ur-gu1d-g035-h3r3"));
            assertTrue(channel.getPodcastLicense().isPresent());
            assertThat(channel.getPodcastLicense().get().getUrl(), isPresentAndIs("https://example.org/mypodcastlicense/full.pdf"));
            assertTrue(channel.getPodcastLocked().isPresent());
            assertThat(channel.getPodcastLocked().get().isLocked(), is(true));
            assertThat(channel.getPodcastLocked().get().getOwner(), isPresentAndIs("podcastowner@example.com"));
            assertThat(channel.getPodcastBlocks().size(), is(3));
            assertThat(channel.getPodcastBlocks().get(0).isBlock(), is(true));
            assertThat(channel.getPodcastBlocks().get(0).getId(), isEmpty());
            assertThat(channel.getPodcastBlocks().get(1).getId(), isPresentAndIs("google"));
            assertThat(channel.getPodcastBlocks().get(1).isBlock(), is(false));
            assertThat(channel.getPodcastBlocks().get(2).getId(), isPresentAndIs("amazon"));
            assertThat(channel.getPodcastBlocks().get(2).isBlock(), is(false));
            assertThat(channel.getPodcastFundings().size(), is(1));
            assertThat(channel.getPodcastFundings().get(0).getFunding(), is("Support the show!"));
            assertThat(channel.getPodcastFundings().get(0).getUrl(), is("https://example.com/donate"));
            assertThat(channel.getPodcastLocations().size(), is(1));
            assertThat(channel.getPodcastLocations().get(0).getLocation(), is("Austin, TX"));
            assertThat(channel.getPodcastLocations().get(0).getGeo(), isPresentAndIs("geo:30.2672,97.7431"));
            assertThat(channel.getPodcastLocations().get(0).getOsm(), isPresentAndIs("R113314"));
            assertThat(channel.getPodcastMedium(), is("podcast"));
            assertThat(channel.getItunesAuthor(), isPresentAndIs("John Doe"));
            assertThat(channel.getItunesExplicit(), is(false));
            assertThat(channel.getItunesType(), isPresentAndIs("episodic"));
            assertThat(channel.getItunesCategories().size(), is(2));
            assertThat(channel.getItunesCategories().get(0), is("News"));
            assertThat(channel.getItunesCategories().get(1), is("Technology"));
            assertTrue(channel.getItunesOwner().isPresent());
            assertThat(channel.getItunesOwner().get().getName(), isPresentAndIs("John Doe"));
            assertThat(channel.getItunesOwner().get().getEmail(), is("johndoe@example.com"));
            assertThat(channel.getItunesImage(), is("https://example.com/images/pci_avatar-massive.jpg"));
            assertThat(channel.getPodcastValues().size(), is(1));
            assertThat(channel.getPodcastValues().get(0).getType(), is("lightning"));
            assertThat(channel.getPodcastValues().get(0).getMethod(), is("keysend"));
            assertThat(channel.getPodcastValues().get(0).getSuggested(), isPresentAndIs(0.00000005000));
            assertThat(channel.getPodcastValues().get(0).getValueRecipients().size(), is(2));
            assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(0).getName(), is("podcaster"));
            assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(0).getType(), is("node"));
            assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(0).getAddress(), is("036557ea56b3b86f08be31bcd2557cae8021b0e3a9413f0c0e52625c6696972e57"));
            assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(0).getSplit(), is(99));
            assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(0).getCustomKey(), isPresentAndIs("channelKey"));
            assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(0).getCustomValue(), isPresentAndIs("channelValue"));
            assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(0).isFee(), is(true));
            assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(1).getName(), is("hosting company"));
            assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(1).getType(), is("node"));
            assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(1).getAddress(), is("036557ea56b3b86f08be31bcd2557cae8021b0e3a9413f0c0e52625c6696972e58"));
            assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(1).getSplit(), is(1));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().size(), is(2));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getStartTime(), is(60));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getStartTimeAsDuration(), is(Duration.ofSeconds(60)));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getDuration(), is(237));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getDurationAsDuration(), is(Duration.ofSeconds(237)));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteStartTime(), isPresentAndIs(174));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteStartTimeAsDuration(), isPresentAndIs(Duration.ofSeconds(174)));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemotePercentage(), isPresentAndIs(95));
            assertTrue(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteItem().isPresent());
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteItem().get().getItemGuid(), isPresentAndIs("asdf089j0-ep240-20230510"));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteItem().get().getFeedGuid(), is("917393e3-1b1e-5cef-ace4-edaa54e1f810"));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteItem().get().getFeedUrl(), isPresentAndIs("https://feeds.example.org/917393e3-1b1e-5cef-ace4-edaa54e1f810/rss.xml"));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteItem().get().getMedium(), isPresentAndIs("music"));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteItem().get().getTitle(), isPresentAndIs("Here Comes the Sun"));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(1).getStartTime(), is(367));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(1).getDuration(), is(246));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().size(), is(2));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(0).getName(), is("Alice (Podcaster)"));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(0).getType(), is("node"));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(0).getAddress(), is("02d5c1bf8b940dc9cadca86d1b0a3c37fbe39cee4c7e839e33bef9174531d27f52"));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(0).getSplit(), is(85));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(1).getName(), is("Bobjim (Guest)"));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(1).getType(), is("node"));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(1).getAddress(), is("032f4ffbbafffbe51726ad3c164a3d0d37ec27bc67b29a159b0f49ae8ac21b8508"));
            assertThat(channel.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(1).getSplit(), is(10));
            assertThat(channel.getPodcastTrailers().size(), is(1));
            assertThat(channel.getPodcastTrailers().get(0).getTrailer(), is("Coming April 1st, 2021"));
            assertThat(channel.getPodcastTrailers().get(0).getPubDate(), is("Thu, 01 Apr 2021 08:00:00 EST"));
            assertThat(channel.getPodcastTrailers().get(0).getPubDateAsZonedDateTime(), is(Default.getDateTimeParser().parse("Thu, 01 Apr 2021 08:00:00 EST")));
            assertThat(channel.getPodcastTrailers().get(0).getUrl(), is("https://example.org/trailers/teaser"));
            assertThat(channel.getPodcastTrailers().get(0).getLength(), is(12345678L));
            assertThat(channel.getPodcastTrailers().get(0).getType(), is("audio/mp3"));
            assertThat(channel.getPodcastTrailers().get(0).getSeason(), isPresentAndIs(2));
            assertTrue(channel.getPodcastChat().isPresent());
            assertThat(channel.getPodcastChat().get().getServer(), is("irc.zeronode.net"));
            assertThat(channel.getPodcastChat().get().getProtocol(), is("irc"));
            assertThat(channel.getPodcastChat().get().getAccountId(), is("@jsmith"));
            assertThat(channel.getPodcastChat().get().getSpace(), isPresentAndIs("#myawesomepodcast"));
            assertThat(channel.getPodcastTxts().size(), is(3));
            assertThat(channel.getPodcastTxts().get(0).getTxt(), is("naj3eEZaWVVY9a38uhX8FekACyhtqP4JO"));
            assertThat(channel.getPodcastTxts().get(0).getPurpose(), isEmpty());
            assertThat(channel.getPodcastTxts().get(1).getTxt(), is("S6lpp-7ZCn8-dZfGc-OoyaH"));
            assertThat(channel.getPodcastTxts().get(1).getPurpose(), isPresentAndIs("verify"));
            assertThat(channel.getPodcastTxts().get(2).getTxt(), is("05125"));
            assertThat(channel.getPodcastTxts().get(2).getPurpose(), isPresentAndIs("applepodcastsverify"));
            assertThat(channel.getPodcastImages().size(), is(4));
            assertThat(channel.getPodcastImages().get(0).getHref(), is("https://example.com/images/channel/pci_avatar-massive.jpg"));
            assertThat(channel.getPodcastImages().get(0).getWidth(), isPresentAndIs(1500));
            assertThat(channel.getPodcastImages().get(1).getHref(), is("https://example.com/images/channel/pci_avatar-middle.jpg"));
            assertThat(channel.getPodcastImages().get(1).getWidth(), isPresentAndIs(600));
            assertThat(channel.getPodcastImages().get(2).getHref(), is("https://example.com/images/channel/pci_avatar-small.jpg"));
            assertThat(channel.getPodcastImages().get(2).getWidth(), isPresentAndIs(300));
            assertThat(channel.getPodcastImages().get(3).getHref(), is("https://example.com/images/channel/pci_avatar-tiny.jpg"));
            assertThat(channel.getPodcastImages().get(3).getWidth(), isPresentAndIs(150));
            assertThat(channel.isPodcastUsingPodping(), isEmpty());
        }

        var item = items.get(1);
        assertThat(item.getTitle(), isPresentAndIs("Episode 3 - The Future"));
        assertThat(item.getDescription(), isPresentAndIs("<p>A look into the future of podcasting and how we get to Podcasting 2.0!</p>"));
        assertThat(item.getLink(), isPresentAndIs("https://example.com/podcast/ep0003"));
        assertThat(item.getGuid(), isPresentAndIs("https://example.com/ep0003"));
        assertThat(item.getIsPermaLink(), isPresentAndIs(true));
        assertThat(item.getPubDate(), isPresentAndIs("Fri, 09 Oct 2020 04:30:38 GMT"));
        assertThat(item.getPubDateAsZonedDateTime(), isPresentAndIs(Default.getDateTimeParser().parse("Fri, 09 Oct 2020 04:30:38 GMT")));
        assertThat(item.getPubDateZonedDateTime(), isPresentAndIs(Default.getDateTimeParser().parse("Fri, 09 Oct 2020 04:30:38 GMT")));
        assertThat(item.getAuthor(), isPresentAndIs("John Doe (john@example.com)"));
        assertThat(item.getItunesImage(), isPresentAndIs("https://example.com/ep0003/artMd.jpg"));
        assertThat(item.getPodcastImages().size(), is(4));
        assertThat(item.getPodcastImages().get(0).getHref(), is("https://example.com/images/ep3/pci_avatar-massive.jpg"));
        assertThat(item.getPodcastImages().get(0).getWidth(), isPresentAndIs(1500));
        assertThat(item.getPodcastImages().get(1).getHref(), is("https://example.com/images/ep3/pci_avatar-middle.jpg"));
        assertThat(item.getPodcastImages().get(1).getWidth(), isPresentAndIs(600));
        assertThat(item.getPodcastImages().get(2).getHref(), is("https://example.com/images/ep3/pci_avatar-small.jpg"));
        assertThat(item.getPodcastImages().get(2).getWidth(), isPresentAndIs(300));
        assertThat(item.getPodcastImages().get(3).getHref(), is("https://example.com/images/ep3/pci_avatar-tiny.jpg"));
        assertThat(item.getPodcastImages().get(3).getWidth(), isPresentAndIs(150));
        assertThat(item.isItunesExplicit(), is(false));
        assertTrue(item.getPodcastSeason().isPresent());
        assertThat(item.getPodcastSeason().get().getSeason(), is(1));
        assertThat(item.getPodcastSeason().get().getName(), isPresentAndIs("Podcasting 2.0"));
        assertTrue(item.getPodcastEpisode().isPresent());
        assertThat(item.getPodcastEpisode().get().getEpisode(), is(1.3d));
        assertThat(item.getPodcastEpisode().get().getDisplay(), isPresentAndIs("S1E3"));
        assertTrue(item.getPodcastChapters().isPresent());
        assertThat(item.getPodcastChapters().get().getUrl(), is("https://example.com/ep3_chapters.json"));
        assertThat(item.getPodcastChapters().get().getType(), is("application/json"));
        assertThat(item.getPodcastSoundbites().size(), is(1));
        assertThat(item.getPodcastSoundbites().get(0).getStartTime(), is(33.833));
        assertThat(item.getPodcastSoundbites().get(0).getStartTimeAsDuration(), is(Duration.ofMillis(33833)));
        assertThat(item.getPodcastSoundbites().get(0).getDuration(), is(42.25));
        assertThat(item.getPodcastSoundbites().get(0).getDurationAsDuration(), is(Duration.ofMillis(42250)));
        assertThat(item.getPodcastSoundbites().get(0).getSoundbite(), isPresentAndIs("Why the Podcast Namespace Matters"));
        assertThat(item.getPodcastTranscripts().size(), is(2));
        assertThat(item.getPodcastTranscripts().get(0).getUrl(), is("https://example.com/ep3/transcript.txt"));
        assertThat(item.getPodcastTranscripts().get(0).getType(), is("text/plain"));
        assertThat(item.getPodcastTranscripts().get(1).getUrl(), is("https://example.com/episode1/transcript.json"));
        assertThat(item.getPodcastTranscripts().get(1).getType(), is("application/json"));
        assertThat(item.getPodcastTranscripts().get(1).getLanguage(), isPresentAndIs("es"));
        assertThat(item.getPodcastTranscripts().get(1).getRel(), isPresentAndIs("captions"));
        assertThat(item.getPodcastPersons().size(), is(3));
        assertThat(item.getPodcastPersons().get(0).getPerson(), is("Adam Curry"));
        assertThat(item.getPodcastPersons().get(0).getHref(), isPresentAndIs("https://www.podchaser.com/creators/adam-curry-107ZzmWE5f"));
        assertThat(item.getPodcastPersons().get(0).getImg(), isPresentAndIs("https://example.com/images/adamcurry.jpg"));
        assertThat(item.getPodcastPersons().get(1).getPerson(), is("Dave Jones"));
        assertThat(item.getPodcastPersons().get(1).getRole(), isPresentAndIs("guest"));
        assertThat(item.getPodcastPersons().get(1).getHref(), isPresentAndIs("https://github.com/daveajones/"));
        assertThat(item.getPodcastPersons().get(1).getImg(), isPresentAndIs("https://example.com/images/davejones.jpg"));
        assertThat(item.getPodcastPersons().get(2).getPerson(), is("Becky Smith"));
        assertThat(item.getPodcastPersons().get(2).getGroup(), isPresentAndIs("visuals"));
        assertThat(item.getPodcastPersons().get(2).getRole(), isPresentAndIs("cover art designer"));
        assertThat(item.getPodcastPersons().get(2).getHref(), isPresentAndIs("https://example.com/artist/beckysmith"));
        assertThat(item.getEnclosures().size(), is(1));
        assertThat(item.getEnclosures().get(0).getUrl(), is("https://example.com/file-03.mp3"));
        assertThat(item.getEnclosures().get(0).getLength(), isPresentAndIs(43200000L));
        assertThat(item.getEnclosures().get(0).getType(), is("audio/mpeg"));
        assertThat(item.getPodcastAlternateEnclosures().size(), is(5));
        assertThat(item.getPodcastAlternateEnclosures().get(0).getType(), is("audio/mpeg"));
        assertThat(item.getPodcastAlternateEnclosures().get(0).getLength(), is(43200000L));
        assertThat(item.getPodcastAlternateEnclosures().get(0).getBitrate(), is(128000d));
        assertThat(item.getPodcastAlternateEnclosures().get(0).isDefaults(), is(true));
        assertThat(item.getPodcastAlternateEnclosures().get(0).getTitle(), is("Standard"));
        assertThat(item.getPodcastAlternateEnclosures().get(0).getSources().size(), is(2));
        assertThat(item.getPodcastAlternateEnclosures().get(0).getSources().get(0).getUri(), is("https://example.com/file-03.mp3"));
        assertThat(item.getPodcastAlternateEnclosures().get(0).getSources().get(1).getUri(), is("https://example.com/file-720.torrent"));
        assertThat(item.getPodcastAlternateEnclosures().get(0).getSources().get(1).getContentType(), isPresentAndIs("application/x-bittorrent"));
        assertThat(item.getPodcastAlternateEnclosures().get(4).getType(), is("video/mp4"));
        assertThat(item.getPodcastAlternateEnclosures().get(4).getLength(), is(7924786L));
        assertThat(item.getPodcastAlternateEnclosures().get(4).getBitrate(), is(511276.52d));
        assertThat(item.getPodcastAlternateEnclosures().get(4).getHeight(), is(720));
        assertThat(item.getPodcastAlternateEnclosures().get(4).getTitle(), is("Video version"));
        assertThat(item.getPodcastAlternateEnclosures().get(4).getSources().size(), is(2));
        assertThat(item.getPodcastAlternateEnclosures().get(4).getSources().get(0).getUri(), is("https://example.com/file-720.mp4"));
        assertThat(item.getPodcastAlternateEnclosures().get(4).getSources().get(1).getUri(), is("ipfs://QmX33FYehk6ckGQ6g1D9D3FqZPix5JpKstKQKbaS8quUFb"));
        assertTrue(item.getPodcastAlternateEnclosures().get(4).getIntegrity().isPresent());
        assertThat(item.getPodcastAlternateEnclosures().get(4).getIntegrity().get().getType(), is("sri"));
        assertThat(item.getPodcastAlternateEnclosures().get(4).getIntegrity().get().getValue(), is("sha384-ExVqijgYHm15PqQqdXfW95x+Rs6C+d6E/ICxyQOeFevnxNLR/wtJNrNYTjIysUBo"));
        assertThat(item.getPodcastValues().size(), is(1));
        assertThat(item.getPodcastValues().get(0).getType(), is("lightning"));
        assertThat(item.getPodcastValues().get(0).getMethod(), is("keysend"));
        assertThat(item.getPodcastValues().get(0).getSuggested(), isPresentAndIs(0.00000005000d));
        assertThat(item.getPodcastValues().get(0).getValueRecipients().size(), is(3));
        assertThat(item.getPodcastValues().get(0).getValueRecipients().get(0).getName(), is("podcaster"));
        assertThat(item.getPodcastValues().get(0).getValueRecipients().get(0).getType(), is("node"));
        assertThat(item.getPodcastValues().get(0).getValueRecipients().get(0).getAddress(), is("036557ea56b3b86f08be31bcd2557cae8021b0e3a9413f0c0e52625c6696972e57"));
        assertThat(item.getPodcastValues().get(0).getValueRecipients().get(0).getSplit(), is(49));
        assertThat(item.getPodcastValues().get(0).getValueRecipients().get(0).getCustomKey(), isPresentAndIs("itemKey"));
        assertThat(item.getPodcastValues().get(0).getValueRecipients().get(0).getCustomValue(), isPresentAndIs("itemValue"));
        assertThat(item.getPodcastValues().get(0).getValueRecipients().get(0).isFee(), is(true));
        assertThat(item.getPodcastValues().get(0).getValueRecipients().get(2).getName(), is("Gigi (Guest)"));
        assertThat(item.getPodcastValues().get(0).getValueRecipients().get(2).getType(), is("node"));
        assertThat(item.getPodcastValues().get(0).getValueRecipients().get(2).getAddress(), is("02e12fea95f576a680ec1938b7ed98ef0855eadeced493566877d404e404bfbf52"));
        assertThat(item.getPodcastValues().get(0).getValueRecipients().get(2).getSplit(), is(50));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().size(), is(2));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(0).getStartTime(), is(60));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(0).getDuration(), is(237));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteStartTime(), isPresentAndIs(175));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemotePercentage(), isPresentAndIs(96));
        assertTrue(item.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteItem().isPresent());
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteItem().get().getItemGuid(), isPresentAndIs("https://podcastindex.org/podcast/4148683#1"));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteItem().get().getFeedGuid(), is("a94f5cc9-8c58-55fc-91fe-a324087a655b"));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(0).getRemoteItem().get().getMedium(), isPresentAndIs("music"));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getStartTime(), is(367));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getDuration(), is(246));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().size(), is(2));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(0).getName(), is("Alice (Podcaster)"));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(0).getType(), is("node"));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(0).getAddress(), is("02d5c1bf8b940dc9cadca86d1b0a3c37fbe39cee4c7e839e33bef9174531d27f52"));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(0).getSplit(), is(85));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(1).getName(), is("Bobjim (Guest)"));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(1).getType(), is("node"));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(1).getAddress(), is("032f4ffbbafffbe51726ad3c164a3d0d37ec27bc67b29a159b0f49ae8ac21b8508"));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getValueRecipients().get(1).getSplit(), is(10));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getStartTime(), is(367));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getDuration(), is(246));
        assertThat(item.getPodcastValues().get(0).getValueTimeSplits().get(1).getRemotePercentage(), isEmpty());
        assertThat(item.getPodcastSocialInteracts().size(), is(2));
        assertThat(item.getPodcastSocialInteracts().get(0).getPriority(), isPresentAndIs(1));
        assertThat(item.getPodcastSocialInteracts().get(0).getUri(), is("https://podcastindex.social/web/@dave/108013847520053258"));
        assertThat(item.getPodcastSocialInteracts().get(0).getProtocol(), is("activitypub"));
        assertThat(item.getPodcastSocialInteracts().get(0).getAccountId(), isPresentAndIs("@dave"));
        assertThat(item.getPodcastSocialInteracts().get(0).getAccountUrl(), isPresentAndIs("https://podcastindex.social/web/@dave"));
        assertThat(item.getPodcastSocialInteracts().get(1).getPriority(), isPresentAndIs(2));
        assertThat(item.getPodcastSocialInteracts().get(1).getUri(), is("https://twitter.com/PodcastindexOrg/status/1507120226361647115"));
        assertThat(item.getPodcastSocialInteracts().get(1).getProtocol(), is("twitter"));
        assertThat(item.getPodcastSocialInteracts().get(1).getAccountId(), isPresentAndIs("@podcastindexorg"));
        assertThat(item.getPodcastSocialInteracts().get(1).getAccountUrl(), isPresentAndIs("https://twitter.com/PodcastindexOrg"));
        assertThat(item.getPodcastTxts().size(), is(4));
        assertThat(item.getPodcastTxts().get(0).getTxt(), is("naj3eEZaWVVY9a38uhX8FekACyhtqP4JN"));
        assertThat(item.getPodcastTxts().get(0).getPurpose(), isEmpty());
        assertThat(item.getPodcastTxts().get(1).getTxt(), is("S6lpp-7ZCn8-dZfGc-OoyaG"));
        assertThat(item.getPodcastTxts().get(1).getPurpose(), isPresentAndIs("verify"));
        assertThat(item.getPodcastTxts().get(2).getTxt(), is("05124"));
        assertThat(item.getPodcastTxts().get(2).getPurpose(), isPresentAndIs("applepodcastsverify"));
        assertThat(item.getPodcastTxts().get(3).getTxt(), is("2022-10-26T04:45:30.742Z"));
        assertThat(item.getPodcastTxts().get(3).getPurpose(), isPresentAndIs("release"));
    }

    @Test
    @SuppressWarnings({"java:S5961", "java:S5738"})
    void example2() {
        var items = new PodcastRssReader().read(fromFile("podcast/example2.xml"))
                .collect(Collectors.toList());

        assertEquals(3, items.size());
        var item = items.get(0);
        var channel = (PodcastChannelImpl) item.getChannel();
        assertThat(channel.getLink(), is("https://podnews.net"));
        assertThat(channel.getTitle(), is("Podnews Daily - podcast industry news"));
        assertThat(channel.getDescription(), is("Daily news for the podcast and on-demand audio industry - from Apple Podcasts to Spotify, YouTube\n" +
                "            Music to Joe Rogan. Podnews also covers the latest jobs and events and trending shows in a short update\n" +
                "            every weekday. editor@podnews.net - visit https://podnews.net to get our free newsletter."));
        assertThat(channel.getLanguage(), isPresentAndIs("en-gb"));
        assertThat(channel.getGenerator(), isPresentAndIs("Podnews LLC"));
        assertThat(channel.getItunesNewFeedUrl(), isPresentAndIs("https://podnews.net/rss"));
        assertThat(channel.getLastBuildDate(), isPresentAndIs("Sat, 27 Sep 2025 11:00:18 +0000"));
        assertThat(channel.getLastBuildDateAsZonedDateTime(), isPresentAndIs(Default.getDateTimeParser().parse("Sat, 27 Sep 2025 11:00:18 +0000")));
        assertThat(channel.getLastBuildDateZonedDateTime(), isPresentAndIs(Default.getDateTimeParser().parse("Sat, 27 Sep 2025 11:00:18 +0000")));
        assertThat(channel.getPodcastLocations().size(), is(1));
        assertThat(channel.getPodcastLocations().get(0).getLocation(), is("Brisbane, Australia"));
        assertThat(channel.getPodcastLocations().get(0).getGeo(), isPresentAndIs("geo:-27.4679,153.028"));
        assertThat(channel.getPodcastLocations().get(0).getOsm(), isPresentAndIs("R11677792"));
        assertThat(channel.getPodcastLocations().get(0).getCountry(), isPresentAndIs("au"));
        assertThat(channel.getPodcastLocations().get(0).getRel(), isPresentAndIs("creator"));
        assertThat(channel.getPubDate(), isPresentAndIs("Fri, 26 Sep 2025 09:19:05 +0000"));
        assertThat(channel.getPubDateAsZonedDateTime(), isPresentAndIs(Default.getDateTimeParser().parse("Fri, 26 Sep 2025 09:19:05 +0000")));
        assertThat(channel.getPubDateZonedDateTime(), isPresentAndIs(Default.getDateTimeParser().parse("Fri, 26 Sep 2025 09:19:05 +0000")));
        assertThat(channel.getSkipDays(), is(List.of("Saturday", "Sunday")));
        assertThat(channel.getSkipHours(), is(List.of(0, 1, 2, 3, 4, 5, 6, 15, 16, 17, 18, 19, 20, 21, 22, 23)));
        assertThat(channel.getPodcastGuid(), is("9b024349-ccf0-5f69-a609-6b82873eab3c"));
        assertThat(channel.getPodcastFundings().size(), is(1));
        assertThat(channel.getPodcastFundings().get(0).getFunding(), is("Support us"));
        assertThat(channel.getPodcastFundings().get(0).getUrl(), is("https://buy.stripe.com/4gw8zIcpc58CcGQ6ot"));
        assertThat(channel.getPodcastValues().size(), is(1));
        assertThat(channel.getPodcastValues().get(0).getType(), is("lightning"));
        assertThat(channel.getPodcastValues().get(0).getMethod(), is("keysend"));
        assertThat(channel.getPodcastValues().get(0).getSuggested(), isPresentAndIs(0.00000100000));
        assertThat(channel.getPodcastValues().get(0).getValueRecipients().size(), is(3));
        assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(0).getName(), is("Podnews via node"));
        assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(0).getType(), is("node"));
        assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(0).getAddress(), is("02b307fdad2e68d08ba5a59cfc8a0a7ec0ff375291e1082fa22a5524e68608c520"));
        assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(0).getSplit(), is(49));
        assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(2).getName(), is("Podcast Index"));
        assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(2).getType(), is("node"));
        assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(2).getAddress(), is("03ae9f91a0cb8ff43840e3c322c4c61f019d8c1c3cea15a25cfc425ac605e61a4a"));
        assertThat(channel.getPodcastValues().get(0).getValueRecipients().get(2).getSplit(), is(2));
        assertThat(channel.isPodcastUsingPodping(), isPresentAndIs(true));
        assertThat(channel.getPodcastPersons().size(), is(1));
        assertThat(channel.getPodcastPersons().get(0).getPerson(), is("James Cridland"));
        assertThat(channel.getPodcastPersons().get(0).getRole(), isPresentAndIs("host"));
        assertThat(channel.getPodcastPersons().get(0).getGroup(), isPresentAndIs("cast"));
        assertThat(channel.getPodcastPersons().get(0).getImg(), isPresentAndIs("https://james.cridland.net/james-cridland-thumbnail.jpg"));
        assertThat(channel.getPodcastPersons().get(0).getHref(), isPresentAndIs("https://james.cridland.net/"));
        assertThat(channel.getItunesAuthor(), isPresentAndIs("Podnews LLC"));
        assertTrue(channel.getItunesOwner().isPresent());
        assertThat(channel.getItunesOwner().get().getEmail(), is("editor+dailyrss@podnews.net"));
        assertThat(channel.getItunesOwner().get().getName(), isPresentAndIs("Podnews LLC"));
        assertThat(channel.getItunesSubtitle(), isPresentAndIs("Daily news for the podcast and on-demand audio industry - from Apple Podcasts to Spotify,\n" +
                "            YouTube Music to Joe Rogan. Podnews also covers the latest jobs and events and trending shows in a short\n" +
                "            update every weekday. editor@podnews.net"));
        assertThat(channel.getItunesCategories(), is(List.of("News", "Daily News", "Technology")));
        assertThat(channel.getItunesType(), isPresentAndIs("episodic"));
        assertThat(channel.getItunesImage(), is("https://podnews.net/static/podnews-2000x2000.png"));
        assertTrue(channel.getImage().isPresent());
        assertThat(channel.getImage().get().getUrl(), is("https://podnews.net/static/_favicons/apple-icon.png"));
        assertThat(channel.getImage().get().getTitle(), is("Podnews"));
        assertThat(channel.getImage().get().getLink(), is("https://podnews.net"));
        assertTrue(channel.getPodcastUpdateFrequency().isPresent());
        assertThat(channel.getPodcastUpdateFrequency().get().isComplete(), is(true));
        assertThat(channel.getPodcastUpdateFrequency().get().getDtstart(), isPresentAndIs("2025-01-01T00:00:00.000Z"));
        assertThat(channel.getPodcastUpdateFrequency().get().getDtstartAsZonedDateTime(), isPresentAndIs(Default.getDateTimeParser().parse("2025-01-01T00:00:00.000Z")));
        assertThat(channel.getPodcastUpdateFrequency().get().getUpdateFrequency(), is("Every weekday"));
        assertThat(channel.getPodcastUpdateFrequency().get().getRrule(), is("FREQ=DAILY;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR"));

        assertThat(channel.getPodcastPodrolls().size(), is(3));
        assertThat(channel.getPodcastPodrolls().get(0).getFeedGuid(), is("396d9ae0-da7e-5557-b894-b606231fa3ea"));
        assertThat(channel.getPodcastPodrolls().get(0).getFeedUrl(), isPresentAndIs("https://feeds.buzzsprout.com/1538779.rss"));
        assertThat(channel.getPodcastPodrolls().get(1).getFeedGuid(), is("d04f3195-25e8-52d9-b87f-969251009f1e"));
        assertThat(channel.getPodcastPodrolls().get(1).getFeedUrl(), isPresentAndIs("https://feeds.buzzsprout.com/2105583.rss"));
        assertThat(channel.getPodcastPodrolls().get(2).getFeedGuid(), is("dc87f50b-8c0d-5980-8f2d-067dde67c7e4"));
        assertThat(channel.getPodcastPodrolls().get(2).getFeedUrl(), isPresentAndIs("https://podnews.net/sitemap/trailers.xml"));
        assertTrue(channel.getPodcastPublisher().isPresent());
        assertThat(channel.getPodcastPublisher().get().getFeedGuid(), is("d76ccec7-e6df-5616-9d7d-8dc1fb9d9820"));
        assertThat(channel.getPodcastPublisher().get().getMedium(), isPresentAndIs("publisher"));
        assertThat(channel.getPodcastPublisher().get().getFeedUrl(), isPresentAndIs("https://podnews.net/static/feeds/publisher.xml"));

        assertThat(channel.getPodcastImages().size(), is(2));
        assertThat(channel.getPodcastImages().get(0).getHref(), is("https://example.com/images/channel/pci_square-massive.jpg"));
        assertThat(channel.getPodcastImages().get(1).getAlt(), isPresentAndIs("An antenna emanating signal waves channel"));
        assertThat(channel.getPodcastImages().get(1).getPurpose(), isPresentAndIs("channel artwork social"));
        assertThat(channel.getPodcastImages().get(1).getType(), isPresentAndIs("image/png"));
        assertThat(channel.getPodcastImages().get(1).getAspectRatio(), isPresentAndIs("9/16"));
        assertThat(channel.getPodcastImages().get(1).getWidth(), isPresentAndIs(90));
        assertThat(channel.getPodcastImages().get(1).getHeight(), isPresentAndIs(160));
        assertThat(channel.getPodcastImages().get(1).getHref(), is("https://example.com/images/channel/pci_landscape-massive.jpg"));

        assertThat(channel.getCategories(), is(List.of("podcasting", "radio")));
        assertThat(channel.getTtl(), isPresentAndIs("30"));

        assertThat(item.getPodcastImages().size(), is(1));
        assertThat(item.getPodcastImages().get(0).getAlt(), isPresentAndIs("An antenna emanating signal waves"));
        assertThat(item.getPodcastImages().get(0).getPurpose(), isPresentAndIs("artwork social"));
        assertThat(item.getPodcastImages().get(0).getType(), isPresentAndIs("image/jpeg"));
        assertThat(item.getPodcastImages().get(0).getAspectRatio(), isPresentAndIs("16/9"));
        assertThat(item.getPodcastImages().get(0).getWidth(), isPresentAndIs(1600));
        assertThat(item.getPodcastImages().get(0).getHeight(), isPresentAndIs(900));
        assertThat(item.getPodcastImages().get(0).getHref(), is("https://example.com/images/ep1/pci_landscape-massive.jpg"));
    }

    @Test
    void equalsContract() {
        EqualsVerifier.simple().forClass(PodcastChannelImpl.class).withNonnullFields("data").withIgnoredFields("dateTimeParser").withIgnoredFields("category").withNonnullFields("categories").withIgnoredFields("syUpdatePeriod").withIgnoredFields("syUpdateFrequency").verify();
        EqualsVerifier.simple().forClass(PodcastItemImpl.class).withNonnullFields("data").withIgnoredFields("defaultComparator").withIgnoredFields("dateTimeParser").withIgnoredFields("category").withNonnullFields("categories").withIgnoredFields("enclosure").withNonnullFields("enclosures").verify();
        EqualsVerifier.simple().forClass(PodcastChapters.class).verify();
        EqualsVerifier.simple().forClass(PodcastAlternateEnclosure.class).verify();
        EqualsVerifier.simple().forClass(PodcastBlock.class).verify();
        EqualsVerifier.simple().forClass(PodcastChat.class).verify();
        EqualsVerifier.simple().forClass(PodcastContentLink.class).verify();
        EqualsVerifier.simple().forClass(PodcastEpisode.class).verify();
        EqualsVerifier.simple().forClass(PodcastFunding.class).verify();
        EqualsVerifier.simple().forClass(PodcastImage.class).verify();
        EqualsVerifier.simple().forClass(PodcastIntegrity.class).verify();
        EqualsVerifier.simple().forClass(PodcastLicense.class).verify();
        EqualsVerifier.simple().forClass(PodcastLocation.class).verify();
        EqualsVerifier.simple().forClass(PodcastLocked.class).verify();
        EqualsVerifier.simple().forClass(PodcastPerson.class).verify();
        EqualsVerifier.simple().forClass(PodcastRemoteItem.class).verify();
        EqualsVerifier.simple().forClass(PodcastSeason.class).verify();
        EqualsVerifier.simple().forClass(PodcastSocialInteract.class).verify();
        EqualsVerifier.simple().forClass(PodcastSoundbite.class).verify();
        EqualsVerifier.simple().forClass(PodcastSource.class).verify();
        EqualsVerifier.simple().forClass(PodcastTrailer.class).withIgnoredFields("dateTimeParser").verify();
        EqualsVerifier.simple().forClass(PodcastTranscript.class).verify();
        EqualsVerifier.simple().forClass(PodcastTxt.class).verify();
        EqualsVerifier.simple().forClass(PodcastUpdateFrequency.class).verify();
        EqualsVerifier.simple().forClass(PodcastValue.class).verify();
        EqualsVerifier.simple().forClass(PodcastValueRecipient.class).verify();
        EqualsVerifier.simple().forClass(PodcastValueTimeSplit.class).verify();
    }

    private InputStream fromFile(String fileName) {
        return getClass().getClassLoader().getResourceAsStream(fileName);
    }
}
